version: '3.9'

services:
  app:
    image: php:8.3-fpm
    container_name: symfony_app
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db
      - redis
    build:
      context: .
      dockerfile: Dockerfile

  webserver:
    image: nginx:alpine
    container_name: symfony_webserver
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8085:80"
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: sym
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  database:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: symfony_user
      PMA_PASSWORD: symfony_password
    ports:
      - "8081:80"
    depends_on:
      - database

  redis:
    image: redis:alpine
    container_name: symfony_redis
    ports:
      - "6379:6379"

volumes:
  db_data:
  postgres_data: