version: '3.9'

services:
  app:
    image: php:8.3-fpm
    container_name: symfony_app
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - database
      - redis
    build:
      context: .
      dockerfile: Dockerfile


  webserver:
    image: nginx:alpine
    container_name: symfony_webserver
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8075:80"
    depends_on:
      - app

  database:
    image: postgres:15
    container_name: symfoby_postgres_db
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database

  redis:
    image: redis:alpine
    container_name: symfony_redis
    ports:
      - "6379:6379"


  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8011:8001"
    depends_on:
      - redis

volumes:
  db_data:
  postgres_data: